version: '3.9'
services:
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-rmx&&*om89k!i-m-*%8enmz9m3ri%@hggc&rh9poar=!xzg825
      - DEBUG=True

